# Generated by Django 5.1.3 on 2024-11-21 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_drugpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugpurchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
