# Generated by Django 5.0.6 on 2024-08-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=20)),
                ('nafdac_reg_n', models.CharField(max_length=20)),
                ('batch_n', models.CharField(max_length=20)),
                ('quantity_in_stock', models.CharField(max_length=20)),
                ('mfg_date', models.DateField(max_length=20)),
                ('exp_date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=14)),
                ('facebook_user', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=20)),
                ('nafdac_reg_n', models.CharField(max_length=20)),
                ('batch_n', models.CharField(max_length=20)),
                ('quantity_in_stock', models.CharField(max_length=20)),
                ('mfg_date', models.DateField(max_length=20)),
                ('exp_date', models.DateField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DrugPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("customer_name", models.CharField(max_length=200)),
                ("drug_name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=50)),
                ("price_per_unit", models.DecimalField(max_digits=10, decimal_places=2)),
                ("quantity", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(max_digits=10, decimal_places=2)),
                ("date",models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
    ]
