# Generated by Django 5.0.6 on 2024-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='batch_n',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='exp_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='mfg_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='nafdac_reg_n',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='quantity_in_stock',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='facebook_user',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
